# Generated by Django 5.1.2 on 2025-12-01 09:59

import cloudinary.models
import datetime
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[("MR", "Mr."), ("MRS", "Mrs."), ("MISS", "Miss")],
                        default="MR",
                        max_length=5,
                        verbose_name="Salutation",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=8,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        default=datetime.date(1900, 1, 1), verbose_name="Date of Birth"
                    ),
                ),
                (
                    "birth_country",
                    django_countries.fields.CountryField(
                        default="IR", max_length=2, verbose_name="Country of Birth"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Place of Birth"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("WIDDOW", "Widdow"),
                            ("DEVORCED", "Devorced"),
                            ("UNKOWN", "Unkown"),
                        ],
                        default="UNKOWN",
                        max_length=20,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "identification_means",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("DRIVER_LICENSE", "Driver License"),
                        ],
                        default="NATIONAL_ID",
                        max_length=20,
                        verbose_name="Identification Means",
                    ),
                ),
                (
                    "id_issue_date",
                    models.DateField(
                        default=datetime.date(2000, 1, 1),
                        verbose_name="ID or Passport Issue Date",
                    ),
                ),
                (
                    "id_expiry_date",
                    models.DateField(
                        default=datetime.date(2025, 1, 1),
                        verbose_name="ID or Passport Expiry Date",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Unknown", max_length=30, verbose_name="Nationality"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+98912345678",
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Unknown", max_length=100, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Unknown", max_length=30, verbose_name="City"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="IR", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("SELF_EMPLOYED", "Self Employed"),
                            ("EMPLOYED", "Employed"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("RETIRED", "Retired"),
                            ("STUDENT", "Student"),
                        ],
                        default="UNEMPLOYED",
                        max_length=30,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Employer Name",
                    ),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Annual Income",
                    ),
                ),
                (
                    "date_of_employment",
                    models.DateField(
                        default=datetime.date(2000, 1, 1),
                        verbose_name="Date of Employment",
                    ),
                ),
                (
                    "employer_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Employer Address",
                    ),
                ),
                (
                    "employer_city",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Employer City",
                    ),
                ),
                (
                    "employer_country",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Employer Country",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Photo"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Photo URL"),
                ),
                (
                    "id_photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="default.jpg",
                        max_length=255,
                        null=True,
                        verbose_name="ID Photo",
                    ),
                ),
                (
                    "id_photo_url",
                    models.URLField(blank=True, null=True, verbose_name="ID Photo URL"),
                ),
                (
                    "signature_photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Signiture Photo",
                    ),
                ),
                (
                    "signature_photo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Signiture Photo URL"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[("MR", "Mr."), ("MRS", "Mrs."), ("MISS", "Miss")],
                        max_length=10,
                        verbose_name="Title",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "other_names",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Other Names"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Birth Date")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(max_length=30, verbose_name="Relationship"),
                ),
                (
                    "email_address",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("city", models.CharField(max_length=30, verbose_name="City")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin",
                        to="user_profile.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("profile", "is_primary"),
                        name="unique_primary_next_of_kin",
                    )
                ],
            },
        ),
    ]
