services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:Z
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - .envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - banker_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .envs/.env.local
    volumes:
      - banker_local_db:/var/lib/postgresql/data
    networks:
      - banker_local_nw

  mailpit:
    image: docker.io/axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data_db:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - banker_local_nw
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    networks:
      - banker_local_nw

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - banker_local_nw

  celery-worker:
    <<: *api
    command: /start-celeryworker.sh
  flower:
    <<: *api
    ports:
      - "5555:5555"
    volumes:
      - flower_db:/var/lib/flower_db
    command: /start-flower.sh
  celery-beat:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celerybeat.sh
    env_file:
      - .envs/.env.local
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - banker_local_nw
  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - banker_local_nw

networks:
  banker_local_nw:
    external: true

volumes:
  banker_local_db:
  mailpit_data_db:
  logs_store:
  rabbitmq_data:
  rabbitmq_log:
  flower_db:
