# Generated by Django 5.1.2 on 2025-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_failed_attempts",
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[("active", "Active"), ("locked", "Locked")],
                default="active",
                max_length=10,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("account_executive", "Account Executive"),
                    ("teller", "Teller"),
                    ("branch_manager", "Branch Manager"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="security_question",
            field=models.CharField(
                choices=[
                    ("maiden_name", "What is your mother's maiden name?"),
                    ("favorite_color", "What is your favorite color?"),
                    ("birth_city", "What is the city where you were born?"),
                    (
                        "childhood_friend",
                        "What is the name of your childhood best friend?",
                    ),
                ],
                max_length=30,
                verbose_name="Security Question",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=12, unique=True, verbose_name="Username"),
        ),
    ]
